title = "WhatsUpate"
[services]
  [services.disqus]
    shortname = 'whatsupdate'
  [services.googleAnalytics]
    ID = 'G-4V070KMHQV'
[params]
  ShowCopyRight = true
  #ShowMore = true
  #ShowRSS = true
  keywords = ['whatsupdate', 'whatsupdate.netlify.app', 'whatsupdate. com', 'whatsupdate.netlify .app', 'news', 'live news', 'big news', 'world news', 'technology']
  [params.algolia]
    enabled = true