title = "InfoTrendSpot"
[services]
  [services.disqus]
    shortname = 'whatsupdate'
  [services.googleAnalytics]
    ID = 'G-4V070KMHQV'
[params]
  ShowCopyRight = true
  #ShowMore = true
  #ShowRSS = true
  mydomain = 'https://infotrendspot.org/'
  keywords = ['InfoTrendSpot', 'infotrendspot.org', 'infotrendspot. org', 'infotrendspot. com', 'news', 'live news', 'big news', 'world news', 'technology']
  [params.algolia]
    enabled = true
    appId = 'QJKQYZKQ1F'
    appKey = '5fa0a426a84ac1a01a1b46b1c2b75bbd'
    searchIndex = 'infotrendspot_blog_articles'
  [[params.js]]
    url = 'snap-gallery.js' 
  [[params.js]]
    url = 'instantsearch.min.js' 