title = "WhatsUpate"
[services]
  [services.disqus]
    shortname = 'whatsupdate'
  [services.googleAnalytics]
    ID = 'G-4V070KMHQV'
[params]
  ShowCopyRight = true
  #ShowMore = true
  #ShowRSS = true
  [params.algolia]
    enabled = true